-- str = "";
-- document.querySelectorAll(".icon-lua .name").forEach(name => {
-- 	  str += `shell.run("wget ${location.href}${name.innerText} ${location.pathname.slice(1)}${name.innerText}")\n`
-- })
-- console.log(str)

-- wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/install.lua install.lua

shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/controller.lua griddy/controller.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/controls_tab.lua griddy/controls_tab.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/events.lua griddy/events.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/frame.lua griddy/frame.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/items_tab.lua griddy/items_tab.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/main.lua griddy/main.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/settings_tab.lua griddy/settings_tab.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/strutils.lua griddy/strutils.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/vaults_tab.lua griddy/vaults_tab.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/vaults.lua griddy/vaults.lua")

shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/init.lua griddy/basalt/init.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/loadObjects.lua griddy/basalt/loadObjects.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/main.lua griddy/basalt/main.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugin.lua griddy/basalt/plugin.lua")

shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/basaltDraw.lua griddy/basalt/libraries/basaltDraw.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/basaltEvent.lua griddy/basalt/libraries/basaltEvent.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/basaltLogs.lua griddy/basalt/libraries/basaltLogs.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/basaltMon.lua griddy/basalt/libraries/basaltMon.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/bimg.lua griddy/basalt/libraries/bimg.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/images.lua griddy/basalt/libraries/images.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/process.lua griddy/basalt/libraries/process.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/reactivePrimitives.lua griddy/basalt/libraries/reactivePrimitives.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/tHex.lua griddy/basalt/libraries/tHex.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/utils.lua griddy/basalt/libraries/utils.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/xmlParser.lua griddy/basalt/libraries/xmlParser.lua")

shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/BaseFrame.lua griddy/basalt/objects/BaseFrame.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Button.lua griddy/basalt/objects/Button.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/ChangeableObject.lua griddy/basalt/objects/ChangeableObject.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Checkbox.lua griddy/basalt/objects/Checkbox.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Container.lua griddy/basalt/objects/Container.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Dropdown.lua griddy/basalt/objects/Dropdown.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Flexbox.lua griddy/basalt/objects/Flexbox.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Frame.lua griddy/basalt/objects/Frame.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Graph.lua griddy/basalt/objects/Graph.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Image.lua griddy/basalt/objects/Image.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Input.lua griddy/basalt/objects/Input.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Label.lua griddy/basalt/objects/Label.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/List.lua griddy/basalt/objects/List.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Menubar.lua griddy/basalt/objects/Menubar.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/MonitorFrame.lua griddy/basalt/objects/MonitorFrame.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/MovableFrame.lua griddy/basalt/objects/MovableFrame.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Object.lua griddy/basalt/objects/Object.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Pane.lua griddy/basalt/objects/Pane.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Program.lua griddy/basalt/objects/Program.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Progressbar.lua griddy/basalt/objects/Progressbar.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Radio.lua griddy/basalt/objects/Radio.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/ScrollableFrame.lua griddy/basalt/objects/ScrollableFrame.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Scrollbar.lua griddy/basalt/objects/Scrollbar.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Slider.lua griddy/basalt/objects/Slider.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Switch.lua griddy/basalt/objects/Switch.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Textfield.lua griddy/basalt/objects/Textfield.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Thread.lua griddy/basalt/objects/Thread.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Timer.lua griddy/basalt/objects/Timer.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Treeview.lua griddy/basalt/objects/Treeview.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/VisualObject.lua griddy/basalt/objects/VisualObject.lua")

shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/advancedBackground.lua griddy/basalt/plugins/advancedBackground.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/animations.lua griddy/basalt/plugins/animations.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/basaltAdditions.lua griddy/basalt/plugins/basaltAdditions.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/bigfonts.lua griddy/basalt/plugins/bigfonts.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/border.lua griddy/basalt/plugins/border.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/debug.lua griddy/basalt/plugins/debug.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/dynamicValues.lua griddy/basalt/plugins/dynamicValues.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/pixelbox.lua griddy/basalt/plugins/pixelbox.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/reactive.lua griddy/basalt/plugins/reactive.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/shadow.lua griddy/basalt/plugins/shadow.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/textures.lua griddy/basalt/plugins/textures.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/themes.lua griddy/basalt/plugins/themes.lua")