-- str = "";
-- document.querySelectorAll(".icon-lua .name").forEach(name => {
-- 	  str += `shell.run("wget ${location.href}${name.innerText} ${location.pathname.slice(1)}${name.innerText}")\n`
-- })
-- console.log(str)

-- wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/install.lua install.lua

shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/controller.lua controller.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/controls_tab.lua controls_tab.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/events.lua events.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/frame.lua frame.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/items_tab.lua items_tab.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/main.lua main.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/settings_tab.lua settings_tab.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/strutils.lua strutils.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/vaults_tab.lua vaults_tab.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/vaults.lua vaults.lua")

shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/init.lua basalt/init.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/loadObjects.lua basalt/loadObjects.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/main.lua basalt/main.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugin.lua basalt/plugin.lua")

shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/basaltDraw.lua basalt/libraries/basaltDraw.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/basaltEvent.lua basalt/libraries/basaltEvent.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/basaltLogs.lua basalt/libraries/basaltLogs.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/basaltMon.lua basalt/libraries/basaltMon.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/bimg.lua basalt/libraries/bimg.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/images.lua basalt/libraries/images.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/process.lua basalt/libraries/process.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/reactivePrimitives.lua basalt/libraries/reactivePrimitives.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/tHex.lua basalt/libraries/tHex.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/utils.lua basalt/libraries/utils.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/libraries/xmlParser.lua basalt/libraries/xmlParser.lua")

shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/BaseFrame.lua basalt/objects/BaseFrame.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Button.lua basalt/objects/Button.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/ChangeableObject.lua basalt/objects/ChangeableObject.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Checkbox.lua basalt/objects/Checkbox.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Container.lua basalt/objects/Container.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Dropdown.lua basalt/objects/Dropdown.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Flexbox.lua basalt/objects/Flexbox.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Frame.lua basalt/objects/Frame.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Graph.lua basalt/objects/Graph.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Image.lua basalt/objects/Image.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Input.lua basalt/objects/Input.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Label.lua basalt/objects/Label.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/List.lua basalt/objects/List.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Menubar.lua basalt/objects/Menubar.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/MonitorFrame.lua basalt/objects/MonitorFrame.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/MovableFrame.lua basalt/objects/MovableFrame.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Object.lua basalt/objects/Object.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Pane.lua basalt/objects/Pane.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Program.lua basalt/objects/Program.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Progressbar.lua basalt/objects/Progressbar.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Radio.lua basalt/objects/Radio.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/ScrollableFrame.lua basalt/objects/ScrollableFrame.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Scrollbar.lua basalt/objects/Scrollbar.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Slider.lua basalt/objects/Slider.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Switch.lua basalt/objects/Switch.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Textfield.lua basalt/objects/Textfield.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Thread.lua basalt/objects/Thread.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Timer.lua basalt/objects/Timer.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/Treeview.lua basalt/objects/Treeview.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/objects/VisualObject.lua basalt/objects/VisualObject.lua")

shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/advancedBackground.lua basalt/plugins/advancedBackground.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/animations.lua basalt/plugins/animations.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/basaltAdditions.lua basalt/plugins/basaltAdditions.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/bigfonts.lua basalt/plugins/bigfonts.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/border.lua basalt/plugins/border.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/debug.lua basalt/plugins/debug.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/dynamicValues.lua basalt/plugins/dynamicValues.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/pixelbox.lua basalt/plugins/pixelbox.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/reactive.lua basalt/plugins/reactive.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/shadow.lua basalt/plugins/shadow.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/textures.lua basalt/plugins/textures.lua")
shell.run("wget https://raw.githubusercontent.com/MrDiamondDog/griddyv2/master/basalt/plugins/themes.lua basalt/plugins/themes.lua")